# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(default='Software Engineering', max_length=100)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, help_text='Key day-to-day responsibilities')),
                ('average_salary', models.CharField(default='?6 - ?14 LPA', help_text='e.g. ?8 - ?18 LPA', max_length=100)),
                ('market_demand', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Moderate', 'Moderate')], default='High', max_length=50)),
                ('industry_growth', models.CharField(default='18% Annual Growth', max_length=50)),
                ('icon_class', models.CharField(default='bi-briefcase', help_text='Bootstrap/FontAwesome icon', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming Languages'), ('Framework', 'Frameworks & Libraries'), ('Database', 'Database & Storage'), ('Cloud_DevOps', 'Cloud & DevOps'), ('Core_CS', 'Core Computer Science & Math'), ('Soft_Skills', 'Soft Skills & Aptitude'), ('Domain', 'Domain Specific Knowledge')], default='Programming', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.FloatField(default=7.0, help_text='Required proficiency from 0 to 10')),
                ('importance', models.CharField(choices=[('Essential', 'Essential'), ('Important', 'Important'), ('Nice to Have', 'Nice to Have')], default='Essential', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Relative weight in score calculation')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_requirements', to='careers.skill')),
            ],
            options={
                'unique_together': {('career', 'skill')},
            },
        ),
    ]
