# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_months', models.IntegerField(default=6)),
                ('career', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_template', to='careers.career')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('estimated_weeks', models.IntegerField(default=3)),
                ('learning_outcomes', models.TextField(blank=True, help_text='Bulleted key deliverables')),
                ('skills_covered', models.ManyToManyField(blank=True, related_name='roadmap_stages', to='careers.skill')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='roadmap.roadmaptemplate')),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentRoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmapstage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'stage')},
            },
        ),
    ]
