# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('college', models.CharField(default='Engineering College', max_length=200)),
                ('degree', models.CharField(default='B.Tech', max_length=100)),
                ('branch', models.CharField(default='Computer Science & Engineering', max_length=100)),
                ('graduation_year', models.IntegerField(default=2026)),
                ('cgpa', models.FloatField(default=8.0)),
                ('preferred_work_style', models.CharField(choices=[('Technical', 'Technical / Deep Coding'), ('Analytical', 'Analytical / Data-Driven'), ('Creative', 'Creative / Design-Oriented'), ('Managerial', 'Managerial / Business-Focused')], default='Technical', max_length=50)),
                ('certifications_count', models.IntegerField(default=0)),
                ('projects_count', models.IntegerField(default=0)),
                ('internship_done', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspiring_students', to='careers.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField(default=5.0, help_text='Rating from 0.0 to 10.0')),
                ('verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='careers.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
