# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner (1-2 Weeks)'), ('Intermediate', 'Intermediate (3-5 Weeks)'), ('Advanced', 'Advanced / Capstone (6-8 Weeks)')], default='Intermediate', max_length=50)),
                ('summary', models.CharField(default='Build a real-world hands-on project.', max_length=300)),
                ('description', models.TextField()),
                ('key_features', models.TextField(help_text='Key features to build in the project')),
                ('deliverables', models.TextField(help_text='What student will deliver (Repo, Demo, Report)')),
                ('architecture_overview', models.TextField(blank=True)),
                ('estimated_hours', models.IntegerField(default=40)),
                ('github_starter_url', models.URLField(blank=True, default='https://github.com')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_projects', to='careers.career')),
                ('skills_required', models.ManyToManyField(related_name='project_ideas', to='careers.skill')),
            ],
        ),
    ]
