# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('candidate_name', models.CharField(blank=True, max_length=150)),
                ('detected_email', models.CharField(blank=True, max_length=150)),
                ('detected_phone', models.CharField(blank=True, max_length=50)),
                ('detected_education', models.TextField(blank=True)),
                ('detected_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('relevant_skills', models.JSONField(default=list)),
                ('completeness_score', models.FloatField(default=0.0, help_text='0 to 100 based on structure and sections')),
                ('match_percentage', models.FloatField(default=0.0, help_text='0 to 100 match with target career')),
                ('feedback_notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='students.studentprofile')),
                ('target_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.career')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
