# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Technical', 'Technical / Conceptual'), ('HR', 'HR / Behavioral'), ('System_Design', 'Architecture & Design'), ('Problem_Solving', 'Problem Solving / Scenario')], default='Technical', max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Entry / Beginner'), ('Medium', 'Intermediate'), ('Hard', 'Advanced')], default='Medium', max_length=20)),
                ('question_text', models.TextField()),
                ('reference_answer', models.TextField(help_text='Standard reference answer for NLP semantic matching')),
                ('key_concepts', models.TextField(help_text='Comma-separated mandatory concepts or keywords')),
                ('evaluation_rubric', models.TextField(blank=True, help_text='Specific criteria to look for')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='careers.career')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('total_questions', models.IntegerField(default=5)),
                ('overall_score', models.FloatField(default=0.0, help_text='Aggregated percentage score')),
                ('feedback_summary', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_attempts', to='careers.career')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
                ('nlp_score', models.FloatField(default=0.0, help_text='Final weighted question score 0-100')),
                ('similarity_score', models.FloatField(default=0.0, help_text='TF-IDF Cosine similarity 0-100')),
                ('keyword_coverage', models.FloatField(default=0.0, help_text='Percentage of key concepts covered')),
                ('word_count', models.IntegerField(default=0)),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interviewsession')),
            ],
        ),
    ]
