# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Course', 'Online Course'), ('Tutorial', 'Interactive Tutorial'), ('Book', 'Book / eBook'), ('Documentation', 'Official Documentation'), ('Video', 'Video Series'), ('Certification', 'Certification Path')], default='Course', max_length=50)),
                ('platform', models.CharField(default='Coursera', max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('duration', models.CharField(default='4-6 Weeks', max_length=50)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(max_length=400)),
                ('is_free', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=4.7)),
                ('related_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_resources', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.skill')),
            ],
            options={
                'ordering': ['-rating', 'level'],
            },
        ),
    ]
