# Generated by Django 6.1 on 2026-09-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_score', models.FloatField(help_text='Calibrated suitability percentage (0-100)')),
                ('raw_probability', models.FloatField(help_text='ML model output probability')),
                ('rank', models.IntegerField(default=1)),
                ('model_name', models.CharField(default='Support Vector Machine', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='students.studentprofile')),
            ],
            options={
                'ordering': ['rank', '-suitability_score'],
            },
        ),
    ]
